# Generated by Django 3.1.4 on 2020-12-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
